"""posts table

Revision ID: 282ea2fcd22a
Revises: 738627be68c8
Create Date: 2023-05-20 21:51:09.417722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282ea2fcd22a'
down_revision = '738627be68c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
