"""posts table

Revision ID: 46ddd59875e4
Revises: 282ea2fcd22a
Create Date: 2023-05-20 21:58:41.270042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ddd59875e4'
down_revision = '282ea2fcd22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=31),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=31),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
