"""posts table

Revision ID: 9d1ec620da3b
Revises: 872c9bd6ac75
Create Date: 2023-05-18 21:40:53.751672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1ec620da3b'
down_revision = '872c9bd6ac75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=True)

    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_content_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_content_title'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_title'))

    # ### end Alembic commands ###
