"""posts table

Revision ID: aa95fdc6b7db
Revises: f3e551eced1f
Create Date: 2023-05-10 11:54:28.772965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa95fdc6b7db'
down_revision = 'f3e551eced1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_content',
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('parent')
    )
    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_content_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_content_timestamp'))

    op.drop_table('post_content')
    # ### end Alembic commands ###
