"""posts table

Revision ID: f3e551eced1f
Revises: 1c5279570b67
Create Date: 2023-05-10 09:56:51.536551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e551eced1f'
down_revision = '1c5279570b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
